title:              Tech
email:              dg600123@gmail.com
description:        알아가는걸 좋아하는 주니어 개발자
author:             jokerLdg
baseurl:            ""
url:                "https://jokerldg.github.io"

# Social Profiles
github_username:    jokerLdg

# Build settings
markdown:           kramdown
highlighter: rouge

kramdown:
  input:          GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap 
  

encoding: 'utf-8'

# category
category_path: "category" # <- default value
category_layout: "category.html" # <- default value