title:              Tech
email:              dg600123@gmail.com
description:        ""
author:             jokerLdg
baseurl:            ""
url:                "https://jokerldg.github.io"

# Social Profiles
github_username:    jokerLdg

# Build settings
markdown:           kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap 
  

encoding: 'utf-8'

# category
category_path: "category" # <- default value
category_layout: "category.html" # <- default value